### ISSUE TITLE
bug in Dommaschk field computation, if R0 not equal 1

### ISSUE THREAD

**Issue by fhindenlang** [boutproject/zoidberg#28]
https://github.com/boutproject/zoidberg/blob/6df12093c5bfe64576710e1667fd1edaa4c04306/zoidberg/field.py#L591C1-L593C38

`Bz` is missing the `R_0` factor:
`Bz = diff(self.P, self.Z) ` -> `Bz = R_0 * diff(self.P, self.Z)`

**Comment by bshanahan** [comment]
Fixed in #29
