### ISSUE TITLE
dx / dz is constant

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/zoidberg#8]
https://github.com/boutproject/zoidberg/blob/master/zoidberg/poloidal_grid.py#L476

Probably not correct?

**Comment by ZedThree** [comment]
That's for a "structured poloidal grid", so I think that's correct.

**Comment by dschwoerer** [comment]
![mesh_w7x](https://user-images.githubusercontent.com/5637662/141766826-967359c3-c288-467e-8b3e-1fa248d81e1f.png)

That is my structured poloidal grid ... so I guess it should be changed?

**Comment by bshanahan** [comment]
I would like to ping @bendudson about this. I vaguely remember having a discussion about this with him.
